dist: trusty
language: node_js
node_js:
  - '8'
install:
  - npm install -g codecov
  - npm install
cache:
  directories:
    - node_modules
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - npm run build
  - npm run test
  - if [ "$TRAVIS_BRANCH" == "master" ]; then codecov; fi
deploy:
  provider: npm
  email: john@neetgroup.net
  api_key:
    secure: oo4jJvNSgU6J4yrtCpB5xCXGb4NTIRBXoWD7VAZqK4YHmwfon6Eg73+KmQsVfWmnsYMIYNQOfTDIvkaIkURR20Mp8dIUoktDVgEiQ3nqdXs3uxw5f5RjXG/Fe8p8ZX4MaiNb1rPATNpjF/MlG++LDjjI62Y7rqWJ4szq5eT0JsrkstM1yDhfLb6sb0BJeOUETEnn8unHUnCs2JJZ76haZ0nVAku5CBVWU+yr5nIddr9o6iUC5PUal5f1nJZfrEoxRDN216ZKdz3L3sPipj2Ejd1DxtX+q6ehLHrUHV/42r+UyS8coOWcT3DlOsScklUsVJJgpY6maQclJWbcWuJzDHJEDS1hvoBylbsvFh/LHHN/kHx+m5y9n08D62ZzS5kBt40kmxC7qhwUvtlkvXth+QyEuA8+Ra5bsJKB9if78xvlQV68YLtwROXII+eU+IyNoLmbMfmtpre3P8N7fODMbqb7zqcPgdMu3qzu/XajRhwaSYRO9dVTgNcX0LwwmiKfXpAra12tB1983unG6uIsqClfj1vivDwAGj3XjbgyYogMla+a4ilwxsTz37u9p/ssDtOrB0DiSgLbct/2w+9o1HQnmaGlAZLAUcbpxXv2AJVruYJXjStSxpRs+l2dIDn7Yqq3ie2f+/qV227qM414MMw7p1sWjwmmUSJ5KANP4M0=
  on:
    branch: master
